### ISSUE TITLE
7.5 As a personal trainer I want to be able to indicate which gym amentiies i am certified in using so that i can safely train clients

### ISSUE THREAD

**Issue by DylanCaro22** [saakethkoka/BookATrainer#39]
size : 1

1.Given a trainer is logged in, they should identify what amenities they are certified in

2.Given a specific machine, it should indicate if a trainer is qualified or not using that machine

**Comment by saakethkoka** [comment]
Backend API:

POST /createTrainerCertification -> inputs a new certification to a trainer
{
    "trainer_id" : 3,
    "amenity_name" : "Row"
}

GET /getTrainerCertifications -> returns list of certifications for a trainer

params:
trainer_id = 3
